# Generated by Django 4.2 on 2023-07-17 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hometype', models.CharField(max_length=100, null=True)),
                ('Price', models.CharField(choices=[('1000.00', '1000.00'), ('2000.00', '2000.00'), ('3000.00', '3000.00'), ('4000.00', '4000.00'), ('5000.00', '5000.00'), ('6000.00', '6000.00'), ('7000.00', '7000.00'), ('8000.00', '8000.00'), ('9000.00', '9000.00')], max_length=20)),
                ('Location', models.CharField(choices=[('Naivasha', 'Naivasha'), ('Molo', 'Molo'), ('Gilgil', 'Gilgil'), ('Njoro', 'Njoro'), ('Maai Mahiu', 'Maai Mahiu'), ('Subukia', 'Subukia'), ('Dundori', 'Dundori'), ('Salgaa', 'Salgaa'), ('Mau Narok', 'Mau Narok'), ('Bahati', 'Bahati'), ('Rongai', 'Rongai'), ('Olenguruone', 'Olenguruone')], max_length=100)),
                ('Image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('FOR SALE', 'FOR SALE'), ('FOR RENT', 'FOR RENT')], max_length=50, null=True)),
                ('Bathrooms', models.IntegerField(null=True)),
                ('Bedrooms', models.IntegerField(null=True)),
                ('Sqr_footage', models.FloatField(null=True)),
                ('Agent_no', phone_field.models.PhoneField(max_length=31, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('Text', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='homelisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('FOR SALE', 'FOR SALE'), ('FOR RENT', 'FOR RENT')], max_length=50, null=True)),
                ('hometype', models.CharField(blank=True, choices=[('Land for sale', 'Land for sale'), ('Apartment', 'Apartment'), ('Bedsitter', 'Bedsitter'), ('Office', 'Office'), ('villa', 'villa'), ('Townhouse', 'Townhouse'), ('Single room', 'Single room')], max_length=20, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(choices=[('1000.00', '1000.00'), ('2000.00', '2000.00'), ('3000.00', '3000.00'), ('4000.00', '4000.00'), ('5000.00', '5000.00'), ('6000.00', '6000.00'), ('7000.00', '7000.00'), ('8000.00', '8000.00'), ('9000.00', '9000.00')], max_length=20)),
                ('sqr_footage', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(choices=[('Naivasha', 'Naivasha'), ('Molo', 'Molo'), ('Gilgil', 'Gilgil'), ('Njoro', 'Njoro'), ('Maai Mahiu', 'Maai Mahiu'), ('Subukia', 'Subukia'), ('Dundori', 'Dundori'), ('Salgaa', 'Salgaa'), ('Mau Narok', 'Mau Narok'), ('Bahati', 'Bahati'), ('Rongai', 'Rongai'), ('Olenguruone', 'Olenguruone')], max_length=50)),
                ('agent_no', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('Likes', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduleview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Location', models.CharField(max_length=50)),
                ('Text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Liking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Homelisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home_likes', to='activity.homelisting')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_likes', to='activity.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_likes', to='activity.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='activity.customer')),
            ],
        ),
    ]
