# Generated by Django 4.1 on 2022-09-29 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hometype', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
                ('Price', models.FloatField()),
                ('Location', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='homelisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometype', models.CharField(max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('price', models.CharField(choices=[('1000.00', '1000.00'), ('2000.00', '2000.00'), ('3000.00', '3000.00'), ('4000.00', '4000.00'), ('5000.00', '5000.00'), ('6000.00', '6000.00'), ('7000.00', '7000.00'), ('8000.00', '8000.00'), ('9000.00', '9000.00')], max_length=20)),
                ('sqr_footage', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('agent_no', phone_field.models.PhoneField(max_length=31)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.category')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
