# Generated by Django 4.1 on 2022-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelisting',
            name='price',
            field=models.CharField(choices=[('1000.00', '1000.00'), ('2000.00', '2000.00'), ('3000.00', '3000.00'), ('4000.00', '4000.00'), ('5000.00', '5000.00'), ('6000.00', '6000.00'), ('1000.00', '1000.00'), ('1000.00', '1000.00'), ('1000.00', '1000.00')], max_length=20),
        ),
    ]
