# Generated by Django 4.1 on 2022-11-21 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_alter_homelisting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Liking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='Description',
        ),
        migrations.AddField(
            model_name='home',
            name='Agent_no',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Sqr_footage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='Text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='category',
            field=models.CharField(choices=[('FOR SALE', 'FOR SALE'), ('FOR RENT', 'FOR RENT')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='Hometype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='Location',
            field=models.CharField(choices=[('Naivasha', 'Naivasha'), ('Molo', 'Molo'), ('Gilgil', 'Gilgil'), ('Njoro', 'Njoro'), ('Maai Mahiu', 'Maai Mahiu'), ('Subukia', 'Subukia'), ('Dundori', 'Dundori'), ('Salgaa', 'Salgaa'), ('Mau Narok', 'Mau Narok'), ('Bahati', 'Bahati'), ('Rongai', 'Rongai'), ('Olenguruone', 'Olenguruone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='Price',
            field=models.CharField(choices=[('1000.00', '1000.00'), ('2000.00', '2000.00'), ('3000.00', '3000.00'), ('4000.00', '4000.00'), ('5000.00', '5000.00'), ('6000.00', '6000.00'), ('7000.00', '7000.00'), ('8000.00', '8000.00'), ('9000.00', '9000.00')], max_length=20),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='agent_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='category',
            field=models.CharField(blank=True, choices=[('FOR SALE', 'FOR SALE'), ('FOR RENT', 'FOR RENT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='hometype',
            field=models.CharField(blank=True, choices=[('Land for sale', 'Land for sale'), ('Apartment', 'Apartment'), ('Bedsitter', 'Bedsitter'), ('Office', 'Office'), ('villa', 'villa'), ('Townhouse', 'Townhouse'), ('Single room', 'Single room')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='location',
            field=models.CharField(choices=[('Naivasha', 'Naivasha'), ('Molo', 'Molo'), ('Gilgil', 'Gilgil'), ('Njoro', 'Njoro'), ('Maai Mahiu', 'Maai Mahiu'), ('Subukia', 'Subukia'), ('Dundori', 'Dundori'), ('Salgaa', 'Salgaa'), ('Mau Narok', 'Mau Narok'), ('Bahati', 'Bahati'), ('Rongai', 'Rongai'), ('Olenguruone', 'Olenguruone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='price',
            field=models.CharField(choices=[('1000.00', '1000.00'), ('2000.00', '2000.00'), ('3000.00', '3000.00'), ('4000.00', '4000.00'), ('5000.00', '5000.00'), ('6000.00', '6000.00'), ('7000.00', '7000.00'), ('8000.00', '8000.00'), ('9000.00', '9000.00')], max_length=20),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='sqr_footage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.AddField(
            model_name='liking',
            name='Homelisting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home_likes', to='activity.homelisting'),
        ),
        migrations.AddField(
            model_name='liking',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_likes', to='activity.customer'),
        ),
        migrations.AddField(
            model_name='likes',
            name='Home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_likes', to='activity.home'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='activity.customer'),
        ),
    ]
