# Generated by Django 4.1 on 2022-11-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_comment_contact_likes_liking_remove_home_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelisting',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
