# Generated by Django 4.1 on 2022-11-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_homelisting_bathrooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
