# Generated by Django 4.1 on 2022-11-24 05:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduleview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Phone', phone_field.models.PhoneField(max_length=31)),
                ('date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
