# Generated by Django 4.1 on 2022-11-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_scheduleview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleview',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleview',
            name='date',
            field=models.DateField(),
        ),
    ]
