# Generated by Django 4.1 on 2022-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_scheduleview_phone_alter_scheduleview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleview',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduleview',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
