# Generated by Django 4.1 on 2022-11-24 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_scheduleview_time_alter_scheduleview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
