# Generated by Django 4.1 on 2022-11-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_scheduleview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleview',
            name='date',
            field=models.DateField(),
        ),
    ]
