# Generated by Django 4.1 on 2022-11-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_scheduleview_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleview',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='scheduleview',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='scheduleview',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='scheduleview',
            old_name='text',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='scheduleview',
            old_name='time',
            new_name='Time',
        ),
    ]
