# Generated by Django 4.1 on 2022-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_rename_date_scheduleview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleview',
            name='Location',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
