# Generated by Django 4.1 on 2022-12-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_scheduleview_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewedschedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewd', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('schedules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.scheduleview')),
            ],
        ),
    ]
