# Generated by Django 4.1 on 2022-12-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_viewedschedules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewedschedules',
        ),
    ]
